- name: play01
  hosts: web
  tasks:
  - name: play01 task101
    ansible.builtin.debug:
      msg: "this is play01 task01"

  - name: play01 task102
    ansible.builtin.debug:
      msg: "this is play01 task02"

- name: play02
  tasks:
  - name: play02 task201
    ansible.builtin.debug:
      msg: "this is play02 task01"

  - name: play02 task202
    ansible.builtin.debug:
      msg: "this is play02 task02"
